import {
  Activity,
  BracketsCurly,
  ButtonCursor,
  Camera,
  Carousel,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Cross,
  Cube,
  Cursor,
  EaseInOut,
  Enter,
  Expand,
  FilterOptions,
  FilterTunel,
  Google,
  HandPointer,
  Heart,
  Image,
  Info,
  InputField,
  Layers,
  Loader,
  Map,
  Monitor,
  Moon,
  MouseScroll,
  Out,
  Search,
  Section,
  Settings,
  SideToggle,
  Sort,
  Sun,
  ThreeDCube,
  TriangleDown,
  User,
  UserFill,
  UserPlus,
  Users,
  Vault,
  VerticalDots,
  Workspace,
} from "@/components/icons";
import { Folder } from "lucide-react";

export const CATEGORY_ICONS: Record<
  string,
  React.ComponentType<{ className?: string }>
> = {
  activity: Activity,
  "bracket-curly": BracketsCurly,
  buttonCursor: ButtonCursor,
  camera: Camera,
  carousel: Carousel,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  cross: Cross,
  cube: Cube,
  cursor: Cursor,
  easeInOut: EaseInOut,
  enter: Enter,
  expand: Expand,
  filter: FilterOptions,
  filterTunel: FilterTunel,
  google: Google,
  handPointer: HandPointer,
  heart: Heart,
  image: Image,
  info: Info,
  inputField: InputField,
  layers: Layers,
  loader: Loader,
  map: Map,
  monitor: Monitor,
  moon: Moon,
  "mouse-scroll": MouseScroll,
  out: Out,
  search: Search,
  section: Section,
  settings: Settings,
  "side-toggle": SideToggle,
  sort: Sort,
  sun: Sun,
  "3d-cube": ThreeDCube,
  "triangle-down": TriangleDown,
  user: User,
  "user-fill": UserFill,
  "user-plus": UserPlus,
  users: Users,
  vault: Vault,
  "vertical-dots": VerticalDots,
  workspace: Workspace,
  default: Folder,
};

export function getCategoryIcon(
  iconName: string | null,
): React.ComponentType<{ className?: string }> {
  if (!iconName) return CATEGORY_ICONS.default;
  return CATEGORY_ICONS[iconName] || CATEGORY_ICONS.default;
}
